name: Deploy to Preview Channel on Pull Request
on:
  pull_request_target:
    branches:
      - master
jobs:
  deploy_preview_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm ci
          npm run predeploy:demo
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_NGX_DRAG_RESIZE }}
          projectId: ngx-drag-resize
